### ISSUE TITLE
To merge, or not to merge?

### ISSUE THREAD

**Issue by edmundmiller** [hyulab/PINTS#15]
PINTS can take multiple bams as input and gain some insight from the replicates. 

However, in the CoPro example, the replicates are merged. Is this the prefered way to use it? Or just merge technical replicates and not biological replicates?

https://github.com/nf-core/nascent/blob/4563e74bcb58ecb18a23e9e31a8ebb138623c55d/subworkflows/local/transcript_identification.nf#L33

**Comment by liyao001** [comment]
Based on my observation, the gain from merging replicates (higher signal intensity, and thus more peak calls) outperforms the potential drawbacks (especially when the samples have descent correlation coefficients), considering existing libraries usually have relatively low sequencing depth. So, for now, I would recommend merging replicates first and using the merged file in PINTS.

**Comment by Emiller88** [comment]
Sounds good, I'll get that added! That's just for technical replicates? 

What do you think about circumstances like in this paper https://genome.cshlp.org/content/28/12/1799.abstract where the data set is the same cell line at different time points after viral infection?

**Comment by liyao001** [comment]
When multiple conditions/comparisons are involved, our internal practice is something like the following:

1. merge all reps (both biological and technical) per condition (condition 1, …, condition n)
2. call peaks per merged sample
3. extract read counts in each bio replicate among the union of the peak regions from different conditions (1, …, n)
4. build a read count matrix
5. use DEseq2/edgeR to call deferentially expressed elements so that contrast can be set with ease

For the paper you're referring to, I think there are no replicates for these different conditions. In this case, I will probably run PINTS on each separately.

**Comment by edmundmiller** [comment]
Thanks for the response! I read it awhile ago, just going to close the issue now!
